version: "3"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "23798:${DB_PORT}"
    env_file: ./envs/.env.init
  indexer:
    build: 
      context: .
      dockerfile: ./Dockerfile 
    restart: on-failure
    depends_on: 
      - db
    env_file: ./envs/.env.indexer.example

